import React from 'react';
import { useAuth } from '../context/AuthContext.jsx';
import { useNavigate, Link } from 'react-router-dom';
import { Dumbbell, LogOut, User, Utensils, Activity, TrendingUp, MessageCircle, ArrowRight, Flame, Shield, Scan, Camera } from 'lucide-react';

export default function Dashboard() {
  const { user, logout } = useAuth();
  const navigate = useNavigate();

  const handleLogout = async () => {
    await logout();
    navigate('/login');
  };

  return (
    <div className="min-h-screen bg-slate-950">
      {/* Navbar */}
      <header className="border-b border-slate-800 px-6 py-4 flex items-center justify-between">
        <div className="flex items-center gap-2">
          <div className="w-8 h-8 bg-gradient-to-tr from-violet-600 to-indigo-600 rounded-lg flex items-center justify-center">
            <Dumbbell className="w-4 h-4 text-white" />
          </div>
          <span className="font-black text-white tracking-tight">ASTRA<span className="text-violet-400 font-light">FIT</span></span>
        </div>
        <div className="flex items-center gap-3">
          {user?.role === 'admin' && (
            <Link to="/admin/dashboard" className="flex items-center gap-1.5 text-xs sm:text-sm font-semibold bg-violet-500/10 border border-violet-500/20 text-violet-300 px-3 py-1.5 rounded-xl hover:bg-violet-500/20 transition-all">
              <Shield className="w-4 h-4 text-violet-400" /> Admin Panel 👑
            </Link>
          )}
          <Link to="/habits" className="flex items-center gap-1.5 text-xs sm:text-sm font-semibold bg-amber-500/10 border border-amber-500/20 text-amber-400 px-3 py-1.5 rounded-xl hover:bg-amber-500/20 transition-all">
            <Flame className="w-4 h-4 fill-amber-500" /> Daily Habits
          </Link>
          <div className="flex items-center gap-2 text-slate-300">
            <User className="w-4 h-4 text-violet-400" />
            <span className="text-sm font-medium">{user?.name}</span>
          </div>
          <button onClick={handleLogout}
            className="flex items-center gap-2 text-sm text-slate-400 hover:text-red-400 transition-colors">
            <LogOut className="w-4 h-4" /> Logout
          </button>
        </div>
      </header>

      {/* Main Content */}
      <main className="max-w-6xl mx-auto px-6 py-12">
        <div className="mb-8">
          <h1 className="text-3xl font-black text-white">
            Welcome back, <span className="text-violet-400">{user?.name?.split(' ')[0]}</span> 👋
          </h1>
          <p className="text-slate-400 mt-1">Your AI fitness journey starts here</p>
        </div>

        {/* Stats placeholder grid */}
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 mb-8">
          {['Daily Calories', 'Workouts Done', 'Current Weight', 'Streak'].map((label, i) => (
            <div key={i} className="glass-panel border border-slate-800 rounded-2xl p-5">
              <p className="text-xs text-slate-500 uppercase tracking-wider font-semibold mb-1">{label}</p>
              <p className="text-2xl font-black text-white">—</p>
              <p className="text-xs text-slate-500 mt-1">Complete setup to see data</p>
            </div>
          ))}
        </div>

        {/* Feature Cards */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {[
            { title: 'AI Diet Plan', desc: 'Personalized 7-day meal plan based on your goals', icon: Utensils, color: 'text-emerald-400', bg: 'from-emerald-500/10 to-green-500/5 border-emerald-500/20', link: '/diet', ready: true },
            { title: 'AI Workout Plan', desc: 'Custom weekly training split generated by AI', icon: Activity, color: 'text-violet-400', bg: 'from-violet-500/10 to-indigo-500/5 border-violet-500/20', link: '/workout', ready: true },
            { title: 'Body & Posture Analysis', desc: 'Computer vision landmark scan & posture report', icon: Scan, color: 'text-pink-400', bg: 'from-pink-500/10 to-rose-500/5 border-pink-500/20', link: '/body-analysis', ready: true },
            { title: 'Physique Photo Comparison', desc: 'Side-by-side weekly before/after comparison studio', icon: Camera, color: 'text-indigo-400', bg: 'from-indigo-500/10 to-violet-500/5 border-indigo-500/20', link: '/progress-photos', ready: true },
            { title: 'Progress Tracker', desc: 'Weight trends, body measurements, and scores', icon: TrendingUp, color: 'text-blue-400', bg: 'from-blue-500/10 to-sky-500/5 border-blue-500/20', link: '/progress', ready: true },
            { title: 'AI Chat Coach', desc: 'Ask your AI fitness coach anything, anytime', icon: MessageCircle, color: 'text-pink-400', bg: 'from-pink-500/10 to-rose-500/5 border-pink-500/20', link: '/chat', ready: true },
          ].map((card) => (
            card.ready
              ? <Link key={card.title} to={card.link}
                  className={`glass-panel bg-gradient-to-br ${card.bg} border rounded-2xl p-6 hover:scale-[1.02] transition-all group`}>
                  <div className="flex items-start justify-between mb-4">
                    <div className={`w-10 h-10 rounded-xl bg-slate-900/60 flex items-center justify-center`}>
                      <card.icon className={`w-5 h-5 ${card.color}`} />
                    </div>
                    <ArrowRight className="w-4 h-4 text-slate-500 group-hover:text-white group-hover:translate-x-1 transition-all" />
                  </div>
                  <h3 className="text-base font-bold text-white mb-1">{card.title}</h3>
                  <p className="text-sm text-slate-400">{card.desc}</p>
                </Link>
              : <div key={card.title}
                  className={`glass-panel bg-gradient-to-br ${card.bg} border rounded-2xl p-6 opacity-60`}>
                  <div className="flex items-start justify-between mb-4">
                    <div className="w-10 h-10 rounded-xl bg-slate-900/60 flex items-center justify-center">
                      <card.icon className={`w-5 h-5 ${card.color}`} />
                    </div>
                    <span className="text-xs text-slate-500 bg-slate-800 border border-slate-700 rounded-lg px-2 py-1">Coming soon</span>
                  </div>
                  <h3 className="text-base font-bold text-white mb-1">{card.title}</h3>
                  <p className="text-sm text-slate-400">{card.desc}</p>
                </div>
          ))}
        </div>
      </main>
    </div>
  );
}
