import React from 'react';
import { useAuth } from '../context/AuthContext.jsx';
import { useNavigate } from 'react-router-dom';
import { Dumbbell, LogOut, User } from 'lucide-react';

export default function Dashboard() {
  const { user, logout } = useAuth();
  const navigate = useNavigate();

  const handleLogout = async () => {
    await logout();
    navigate('/login');
  };

  return (
    <div className="min-h-screen bg-slate-950">
      {/* Navbar */}
      <header className="border-b border-slate-800 px-6 py-4 flex items-center justify-between">
        <div className="flex items-center gap-2">
          <div className="w-8 h-8 bg-gradient-to-tr from-violet-600 to-indigo-600 rounded-lg flex items-center justify-center">
            <Dumbbell className="w-4 h-4 text-white" />
          </div>
          <span className="font-black text-white tracking-tight">ASTRA<span className="text-violet-400 font-light">FIT</span></span>
        </div>
        <div className="flex items-center gap-4">
          <div className="flex items-center gap-2 text-slate-300">
            <User className="w-4 h-4 text-violet-400" />
            <span className="text-sm font-medium">{user?.name}</span>
          </div>
          <button onClick={handleLogout}
            className="flex items-center gap-2 text-sm text-slate-400 hover:text-red-400 transition-colors">
            <LogOut className="w-4 h-4" /> Logout
          </button>
        </div>
      </header>

      {/* Main Content */}
      <main className="max-w-6xl mx-auto px-6 py-12">
        <div className="mb-8">
          <h1 className="text-3xl font-black text-white">
            Welcome back, <span className="text-violet-400">{user?.name?.split(' ')[0]}</span> 👋
          </h1>
          <p className="text-slate-400 mt-1">Your AI fitness journey starts here</p>
        </div>

        {/* Stats placeholder grid */}
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 mb-8">
          {['Daily Calories', 'Workouts Done', 'Current Weight', 'Streak'].map((label, i) => (
            <div key={i} className="glass-panel border border-slate-800 rounded-2xl p-5">
              <p className="text-xs text-slate-500 uppercase tracking-wider font-semibold mb-1">{label}</p>
              <p className="text-2xl font-black text-white">—</p>
              <p className="text-xs text-slate-500 mt-1">Complete setup to see data</p>
            </div>
          ))}
        </div>

        {/* Coming soon panels */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {[
            { title: '🥗 AI Diet Plan', desc: 'Personalized meal plan based on your goals & preferences' },
            { title: '💪 AI Workout Plan', desc: 'Custom weekly training split generated by AI' },
            { title: '📊 Progress Tracker', desc: 'Weight trends, body measurements, and fitness scores' },
            { title: '🤖 AI Chat Coach', desc: 'Ask your AI fitness coach anything, anytime' },
          ].map((card, i) => (
            <div key={i} className="glass-panel border border-slate-800 rounded-2xl p-6">
              <h3 className="text-lg font-bold text-white mb-2">{card.title}</h3>
              <p className="text-sm text-slate-400 mb-4">{card.desc}</p>
              <span className="inline-block text-xs text-violet-400 bg-violet-500/10 border border-violet-500/20 rounded-lg px-3 py-1 font-semibold">
                Coming soon...
              </span>
            </div>
          ))}
        </div>
      </main>
    </div>
  );
}
